name: Build project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run build
    - uses: EndBug/add-and-commit@v4
      with:
        add: 'dist'

        author_name: Pug Bot
        author_email: pugmire.bot@gmail.com
        force: true
        message: 'Push new version'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
